services:
  app:
    image: salehghalayini/apexo:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=apexo_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=Abou@li5-3
    volumes:
      - app_storage:/app/storage
    command: >
      /bin/bash -c "
        php artisan config:cache &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: apexo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abou@li5-3
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  app_storage: