services:
  app:
    image: salehghalayini/apexo:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=apexo_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=Abou@li5-3
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  queue:
    image: salehghalayini/apexo:latest
    restart: always
    depends_on:
      - db
    command: php artisan queue:work --tries=3
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=apexo_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=Abou@li5-3
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: apexo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abou@li5-3
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
