version: '3.8'

services:
  app:
    image: salehghalayini/Apexo:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=apexo_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=Abou@li5-3

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: apexo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abou@li5-3
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

