name: Build and Deploy Laravel App

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  Build-And-Push-Docker:
    needs: Run-Laravel-Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/Apexo:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/Apexo:latest

  Deploy-To-Server:
    needs: Build-And-Push-Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker-compose down || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/Apexo:latest
            docker-compose up -d --build
