- name: Setup Node.js environment
  uses: actions/setup-node@v3
  with:
    node-version: "22"
- name: Check Node.js version
  run: node -v
- name: Check npm version
  run: npm -v

- name: Install dependencies
  working-directory: ./client
  run: npm install --legacy-peer-deps
- name: Build React App
  working-directory: ./client
  run: npm run build

- name: Uploading React App to EC2
  uses: appleboy/scp-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_KEY }}
    source: "client/dist"
    target: "/home/${{ secrets.EC2_USER }}/"
- name: Uploading React App to S3
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_KEY }}
    script: |
      mkdir -p ~/.aws
      echo "[default]" > ~/.aws/config
      echo "region = ${{ secrets.AWS_DEFAULT_REGION }}" >> ~/.aws/config
      aws s3 cp client/dist/ s3://fse-final-saleh --recursive --no-sign-request
      rm -r client/
