name: Run Staging Laravel Tests

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  Run-Laravel-Tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Dependencies & Configure Environment
        working-directory: ./server
        run: |
          cp .env.example .env
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=pgsql/' .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=5432/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=testing/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=postgres/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env

          composer install --no-interaction --prefer-dist
          php artisan key:generate --force
          php artisan jwt:secret --force
          php artisan migrate --force

      - name: Run Laravel tests
        working-directory: ./server
        run: php artisan test
